name: release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Instal Rust
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # Run release-plz to create PRs and releases
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
